### PR TITLE
if you already own the stick, just upgrade your stick instead of reje…

### PR DESCRIPTION
**Pull request by janxious**
…cting taking stick ownership

### CODE REVIEW

**Comment by netshade** [comment]
:+1:

**Comment by illbzo1** [comment]
Nice :)

**Comment by tonydewan** [comment]
:ship: that :shipit:

**Comment by janxious** [comment]
@tonydewan How does one ship this project? I feel like the instructions are incorrect in the README.

**Comment by tonydewan** [comment]
The README is correct for a fresh install of flowbort, but not correct for _our_ already-running flowbort. I'll add you to correct places.

**Pull request merged**
